"""Buridan UI Component Registry.

AUTO-GENERATED by scripts/generate_registry.py -- do not edit by hand.
Re-run the script after adding/moving/renaming component files.
"""

COMPONENT_REGISTRY = {
    # --- app/www/library/blocks ---
    "area_chart_01": {
        "files": ["app/www/library/blocks/area_chart_01.py"],
        "dependencies": ["card", "chart_tooltip"],
    },
    "area_chart_02": {
        "files": ["app/www/library/blocks/area_chart_02.py"],
        "dependencies": ["card", "chart_tooltip"],
    },
    "bar_chart_01": {
        "files": ["app/www/library/blocks/bar_chart_01.py"],
        "dependencies": ["card", "chart_tooltip", "checkbox", "field"],
    },
    "bar_chart_02": {
        "files": ["app/www/library/blocks/bar_chart_02.py"],
        "dependencies": ["card", "chart_tooltip"],
    },
    "bar_chart_03": {
        "files": ["app/www/library/blocks/bar_chart_03.py"],
        "dependencies": ["card", "chart_tooltip"],
    },
    "bar_chart_04": {
        "files": ["app/www/library/blocks/bar_chart_04.py"],
        "dependencies": ["card", "chart_tooltip"],
    },
    "kpi_card_01": {
        "files": ["app/www/library/blocks/kpi_card_01.py"],
        "dependencies": ["card"],
    },
    "kpi_card_02": {
        "files": ["app/www/library/blocks/kpi_card_02.py"],
        "dependencies": ["card", "chart_tooltip"],
    },
    "line_chart_01": {
        "files": ["app/www/library/blocks/line_chart_01.py"],
        "dependencies": ["card", "chart_tooltip"],
    },
    "line_chart_02": {
        "files": ["app/www/library/blocks/line_chart_02.py"],
        "dependencies": ["card", "chart_tooltip"],
    },
    "line_chart_03": {
        "files": ["app/www/library/blocks/line_chart_03.py"],
        "dependencies": ["card", "chart_tooltip"],
    },
    "line_chart_04": {
        "files": ["app/www/library/blocks/line_chart_04.py"],
        "dependencies": ["card", "chart_tooltip"],
    },

    # --- components/charts ---
    "chart_tooltip": {
        "files": ["components/charts/chart_tooltip.py"],
        "dependencies": [],
    },

    # --- components/icons ---
    "hugeicon": {
        "files": ["components/icons/hugeicon.py"],
        "dependencies": [],
    },

    # --- components/ui ---
    "accordion": {
        "files": ["components/ui/accordion.py"],
        "dependencies": ["core", "hugeicon"],
    },
    "attachment": {
        "files": ["components/ui/attachment.py"],
        "dependencies": ["button", "core"],
    },
    "autocomplete": {
        "files": ["components/ui/autocomplete.py"],
        "dependencies": ["core"],
    },
    "avatar": {
        "files": ["components/ui/avatar.py"],
        "dependencies": ["core"],
    },
    "badge": {
        "files": ["components/ui/badge.py"],
        "dependencies": ["core"],
    },
    "breadcrumb": {
        "files": ["components/ui/breadcrumb.py"],
        "dependencies": ["core", "hugeicon"],
    },
    "bubble": {
        "files": ["components/ui/bubble.py"],
        "dependencies": ["core"],
    },
    "button": {
        "files": ["components/ui/button.py"],
        "dependencies": ["core"],
    },
    "button_group": {
        "files": ["components/ui/button_group.py"],
        "dependencies": ["core", "separator"],
    },
    "card": {
        "files": ["components/ui/card.py"],
        "dependencies": ["core"],
    },
    "checkbox": {
        "files": ["components/ui/checkbox.py"],
        "dependencies": ["core", "hugeicon"],
    },
    "collapsible": {
        "files": ["components/ui/collapsible.py"],
        "dependencies": ["core"],
    },
    "context_menu": {
        "files": ["components/ui/context_menu.py"],
        "dependencies": ["core", "hugeicon"],
    },
    "core": {
        "files": ["components/ui/core.py"],
        "dependencies": [],
    },
    "dialog": {
        "files": ["components/ui/dialog.py"],
        "dependencies": ["core"],
    },
    "field": {
        "files": ["components/ui/field.py"],
        "dependencies": ["separator"],
    },
    "frame": {
        "files": ["components/ui/frame.py"],
        "dependencies": ["core"],
    },
    "heatmap": {
        "files": ["components/ui/heatmap.py"],
        "dependencies": ["core"],
    },
    "input": {
        "files": ["components/ui/input.py"],
        "dependencies": ["core"],
    },
    "input_group": {
        "files": ["components/ui/input_group.py"],
        "dependencies": ["button", "core", "input", "textarea"],
    },
    "kbd": {
        "files": ["components/ui/kbd.py"],
        "dependencies": ["core"],
    },
    "marker": {
        "files": ["components/ui/marker.py"],
        "dependencies": ["core"],
    },
    "menu": {
        "files": ["components/ui/menu.py"],
        "dependencies": ["core", "hugeicon"],
    },
    "message": {
        "files": ["components/ui/message.py"],
        "dependencies": ["core"],
    },
    "metric": {
        "files": ["components/ui/metric.py"],
        "dependencies": ["core"],
    },
    "popover": {
        "files": ["components/ui/popover.py"],
        "dependencies": ["core"],
    },
    "scroll_area": {
        "files": ["components/ui/scroll_area.py"],
        "dependencies": ["core"],
    },
    "select": {
        "files": ["components/ui/select.py"],
        "dependencies": ["core", "hugeicon"],
    },
    "separator": {
        "files": ["components/ui/separator.py"],
        "dependencies": ["core"],
    },
    "skeleton": {
        "files": ["components/ui/skeleton.py"],
        "dependencies": ["core"],
    },
    "slider": {
        "files": ["components/ui/slider.py"],
        "dependencies": ["core"],
    },
    "spinner": {
        "files": ["components/ui/spinner.py"],
        "dependencies": ["core"],
    },
    "switch": {
        "files": ["components/ui/switch.py"],
        "dependencies": ["core"],
    },
    "table": {
        "files": ["components/ui/table.py"],
        "dependencies": ["core"],
    },
    "tabs": {
        "files": ["components/ui/tabs.py"],
        "dependencies": ["core"],
    },
    "textarea": {
        "files": ["components/ui/textarea.py"],
        "dependencies": ["core"],
    },
    "timeline": {
        "files": ["components/ui/timeline.py"],
        "dependencies": ["core"],
    },
    "toggle": {
        "files": ["components/ui/toggle.py"],
        "dependencies": ["core"],
    },
    "toggle_group": {
        "files": ["components/ui/toggle_group.py"],
        "dependencies": ["core"],
    },
    "tooltip": {
        "files": ["components/ui/tooltip.py"],
        "dependencies": ["core"],
    },
}
