#!/usr/bin/env python3
"""
generate_anatomy.py

Regenerates app/www/anatomy.py (the ANATOMY dict your parser reads) from
real, hand-authored, importable source files in app/www/anatomy_src/.

Why this exists:
    Anatomy compositions (how sub-parts nest) can't be reliably derived
    automatically -- they're a documentation decision, not a fact
    recoverable from the component's code. So you author them by hand,
    same as before. What changes is *where* you author them: instead of a
    string buried in one giant dict, each component gets its own real
    .py file that imports the actual component and builds the actual
    composition:

        # app/www/anatomy_src/accordion.py
        from components.ui.accordion import accordion

        COMPOSITION = accordion.root(
            accordion.item(...),
        )

    This script then:
      1. Parses each file with `ast` and extracts the exact source text
         of the COMPOSITION expression (so what you typed is what gets
         displayed, byte for byte).
      2. Actually IMPORTS each file, which forces Python to build the real
         component tree. If you typo a part name or a method gets renamed
         upstream, this fails loudly right here -- instead of silently
         shipping a broken code sample to users.
      3. Writes the combined app/www/anatomy.py dict, same shape as
         before, so the CLI/render code that does
         `from app.www.anatomy import ANATOMY` needs zero changes.

Usage:
    python scripts/generate_anatomy.py
    python scripts/generate_anatomy.py --check     # CI mode, no write, exit 1 on drift or import errors
    python scripts/generate_anatomy.py --src app/www/anatomy_src --out app/www/anatomy.py
"""

from __future__ import annotations

import argparse
import ast
import importlib.util
import sys
from pathlib import Path

DEFAULT_SRC = "app/anatomy_src"
DEFAULT_OUT = "app/registry/anatomy.py"

# Registry entries that are never expected to have their own anatomy entry:
#   - internal-only helper files (core, hugeicon, chart_tooltip)
#   - anything under app/www/library/blocks/ -- blocks are already complete,
#     pre-assembled examples, not composable primitives, so there's nothing
#     to document a "composition" for.
NOT_USER_FACING = {"core", "hugeicon", "chart_tooltip"}
BLOCK_PATH_PREFIX = "app/www/library/blocks/"


def is_block(name: str, registry: dict) -> bool:
    entry = registry.get(name)
    if not entry:
        return False
    return any(f.startswith(BLOCK_PATH_PREFIX) for f in entry.get("files", []))


def load_registry(repo_root: Path) -> dict:
    sys.path.insert(0, str(repo_root))
    try:
        from app.registry.components import COMPONENT_REGISTRY

        return COMPONENT_REGISTRY
    finally:
        sys.path.pop(0)


def extract_composition_source(path: Path) -> str:
    """Parse the file and return the exact source text of the
    `COMPOSITION = ...` right-hand side, preserving original formatting."""
    text = path.read_text(encoding="utf-8")
    tree = ast.parse(text, filename=str(path))

    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(t, ast.Name) and t.id == "COMPOSITION" for t in node.targets
        ):
            segment = ast.get_source_segment(text, node.value)
            if segment is None:
                raise ValueError(f"Could not extract source for COMPOSITION in {path}")
            return segment

    raise ValueError(f"No top-level `COMPOSITION = ...` assignment found in {path}")


def validate_by_importing(path: Path, repo_root: Path) -> None:
    """Actually import the file so Python builds the real component tree.
    Raises if a part doesn't exist / a call is malformed / etc."""
    module_name = f"_anatomy_validate_{path.stem}"
    spec = importlib.util.spec_from_file_location(module_name, path)
    module = importlib.util.module_from_spec(spec)
    sys.path.insert(0, str(repo_root))
    try:
        spec.loader.exec_module(module)
    finally:
        sys.path.pop(0)

    if not hasattr(module, "COMPOSITION"):
        raise ValueError(f"{path} has no COMPOSITION after import")


def discover_files(src_dir: Path) -> list[Path]:
    return sorted(p for p in src_dir.glob("*.py") if p.name != "__init__.py")


def render_anatomy(entries: dict[str, str]) -> str:
    lines = [
        '"""Buridan UI Anatomy Registry.',
        "",
        "AUTO-GENERATED by scripts/generate_anatomy.py -- do not edit by hand.",
        "Edit the corresponding file in app/www/anatomy_src/ instead, then re-run the script.",
        '"""',
        "",
        "ANATOMY = {",
    ]
    for name in sorted(entries):
        body = entries[name]
        lines.append(f'    "{name}": """{body}""",')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--src",
        default=DEFAULT_SRC,
        help=f"Folder of per-component anatomy source files. Default: {DEFAULT_SRC}",
    )
    parser.add_argument(
        "--out",
        default=DEFAULT_OUT,
        help=f"Output path for the generated ANATOMY dict. Default: {DEFAULT_OUT}",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Don't write. Exit 1 if content would differ, or if any file fails validation.",
    )
    parser.add_argument(
        "--skip-import-validation",
        action="store_true",
        help="Skip actually importing each file (faster, but no correctness check).",
    )
    parser.add_argument(
        "--allow-orphans",
        action="store_true",
        help="Don't fail when an anatomy file references a component no longer in COMPONENT_REGISTRY (just warn).",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    src_dir = repo_root / args.src
    out_path = repo_root / args.out

    if not src_dir.exists():
        print(f"Source folder not found: {src_dir}", file=sys.stderr)
        sys.exit(1)

    files = discover_files(src_dir)
    if not files:
        print(f"No anatomy source files found in {src_dir}", file=sys.stderr)
        sys.exit(1)

    entries: dict[str, str] = {}
    errors: list[str] = []

    for path in files:
        name = path.stem
        try:
            entries[name] = extract_composition_source(path)
            if not args.skip_import_validation:
                validate_by_importing(path, repo_root)
        except Exception as e:  # noqa: BLE001 -- we want to report *any* failure per-file and continue
            errors.append(f"{path.name}: {e}")

    if errors:
        print("Anatomy validation FAILED for:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        sys.exit(1)

    # Cross-check against the registry: an anatomy file whose component no
    # longer exists in COMPONENT_REGISTRY imports fine (the .py file may
    # still physically exist) but is dead weight -- nobody can `buridan add`
    # it anymore. This is the case that import-validation alone can't catch.
    registry = load_registry(repo_root)
    registry_names = set(registry.keys())
    anatomy_names = set(entries.keys())

    orphans = sorted(anatomy_names - registry_names)
    missing = sorted(
        name
        for name in (registry_names - anatomy_names)
        if name not in NOT_USER_FACING and not is_block(name, registry)
    )

    if missing:
        print(
            "No anatomy authored yet for (informational, not failing the build):",
            file=sys.stderr,
        )
        for name in missing:
            print(f"  - {name}", file=sys.stderr)

    if orphans:
        label = "WARNING" if args.allow_orphans else "ERROR"
        print(
            f"{label}: anatomy_src files reference components no longer in COMPONENT_REGISTRY:",
            file=sys.stderr,
        )
        for name in orphans:
            print(
                f"  - {name}.py -- delete this file or re-add '{name}' to the registry",
                file=sys.stderr,
            )
        if not args.allow_orphans:
            sys.exit(1)
        for name in orphans:
            entries.pop(name, None)

    rendered = render_anatomy(entries)

    if args.check:
        existing = out_path.read_text(encoding="utf-8") if out_path.exists() else None
        if existing == rendered:
            print(
                "Anatomy is up to date and all compositions import cleanly.",
                file=sys.stderr,
            )
            sys.exit(0)
        print(
            "Anatomy is OUT OF DATE. Run without --check to regenerate.",
            file=sys.stderr,
        )
        sys.exit(1)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(rendered, encoding="utf-8")
    print(f"Wrote {len(entries)} anatomy entries to {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
